# Generated by Django 6.0.4 on 2026-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
