# Generated by Django 6.0.4 on 2026-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_razorpay_refund_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe')], default='razorpay', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
